name: CI for Pypeaday Hello World

on:
  workflow_dispatch:
  schedule:
    # Run at 10 pm every day
    - cron: '0 22 * * *'
  push:
    branches: [ "main" ]
    paths:
      - 'pypeaday-hello-world/**'
      - '.github/workflows/ci-pypeaday-hello-world.yml'
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3

      - name: pre-commit
        uses: pre-commit/action@v3.0.0
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build the Python Hello World Docker image
        run: docker build ./pypeaday-hello-world --file ./pypeaday-hello-world/Dockerfile --tag pypeaday-hello-world:$GITHUB_RUN_ID-$GITHUB_RUN_NUMBER --tag pypeaday-hello-world:latest

      - name: Run Docker Container
        run: docker run pypeaday-hello-world
  deploy:
    runs-on: ubuntu-latest
    needs: [lint, build]
    steps:
      - name: echo
        run: echo "DEPLOY SOMEWHERE"
